version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: terraform-provider-uptrace
    binary: terraform-provider-uptrace_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: terraform-provider-uptrace
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 \"v1\") }}{{ .Amd64 }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

signs:
  - cmd: gpg
    args:
      - --batch
      - --local-user
      - "{{ .Env.GPG_FINGERPRINT }}"
      - --output
      - "${signature}"
      - --detach-sign
      - "${artifact}"
    artifacts: checksum

changelog:
  sort: asc
  use: github
  abbrev: 0
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^build:"
      - "^style:"
      - "^refactor:"
      - "Merge pull request"
      - "Merge branch"
      - "^fix:.*linter"
      - "^fix:.*golangci"
      - "^fix:.*comment"
  groups:
    - title: "🚀 New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "📚 Documentation"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 2
    - title: "🔧 Other Changes"
      order: 999

release:
  github:
    owner: riccap
    name: tofu-uptrace-provider
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
  header: |
    ## Installation

    Download the appropriate binary for your platform from the assets below, or use Terraform/OpenTofu to install automatically:

    ```hcl
    terraform {
      required_providers {
        uptrace = {
          source  = "github.com/riccap/tofu-uptrace-provider"
          version = "{{ .Version }}"
        }
      }
    }
    ```

    ## What's Changed
  footer: |
    **Full Changelog**: https://github.com/riccap/tofu-uptrace-provider/compare/{{ if .PreviousTag }}{{ .PreviousTag }}{{ else }}{{ .Tag }}{{ end }}...{{ .Tag }}

    ## Documentation

    - [Getting Started Guide](https://github.com/riccap/tofu-uptrace-provider/blob/main/docs/guides/getting-started.md)
    - [Best Practices](https://github.com/riccap/tofu-uptrace-provider/blob/main/docs/guides/best-practices.md)
    - [Resource Documentation](https://github.com/riccap/tofu-uptrace-provider/tree/main/docs/resources)
    - [Examples](https://github.com/riccap/tofu-uptrace-provider/tree/main/examples)
