version: '3'

vars:
  BINARY_NAME: terraform-provider-uptrace
  GOBIN: '{{.ROOT_DIR}}/bin'

env:
  CGO_ENABLED: "0"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  deps:
    desc: Install development dependencies
    cmds:
      - go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@latest
      - go mod download

  generate:
    desc: Generate code from OpenAPI spec
    deps: [deps]
    sources:
      - api/openapi.yaml
      - oapi-codegen.yaml
    generates:
      - internal/client/generated/*.go
    cmds:
      - mkdir -p internal/client/generated
      - oapi-codegen -config oapi-codegen.yaml api/openapi.yaml

  build:
    desc: Build the provider binary
    deps: [generate]
    sources:
      - '**/*.go'
      - go.mod
      - go.sum
    generates:
      - '{{.BINARY_NAME}}'
    cmds:
      - go build -o {{.BINARY_NAME}} -ldflags="-s -w" .

  install:
    desc: Install provider to local Terraform plugins directory
    deps: [build]
    vars:
      VERSION: '0.1.0'
      OS: '{{OS}}'
      ARCH: '{{ARCH}}'
      PLUGIN_DIR: '~/.terraform.d/plugins/registry.terraform.io/riccap/uptrace/{{.VERSION}}/{{.OS}}_{{.ARCH}}'
    cmds:
      - mkdir -p {{.PLUGIN_DIR}}
      - cp {{.BINARY_NAME}} {{.PLUGIN_DIR}}/

  test:
    desc: Run all unit tests
    cmds:
      - go test -v -cover -race -short ./...

  test:unit:
    desc: Run unit tests only (short mode)
    cmds:
      - go test -v -race -short ./...

  test:models:
    desc: Run model conversion tests
    cmds:
      - go test -v -run TestPlanToMonitorInput ./internal/provider/
      - go test -v -run TestMonitorToState ./internal/provider/

  test:coverage:
    desc: Run unit tests with coverage report
    cmds:
      - go test -v -coverprofile=coverage.txt -covermode=atomic -short ./...
      - go tool cover -html=coverage.txt -o coverage.html
      - echo "Unit test coverage report generated at coverage.html"

  test:coverage:unit:
    desc: Run unit tests with coverage (alias for test:coverage)
    cmds:
      - task: test:coverage

  test:coverage:acc:
    desc: Run acceptance tests with coverage report
    deps: [dev:up]
    env:
      TF_ACC: "1"
      UPTRACE_ENDPOINT: "http://localhost:14318/internal/v1"
      UPTRACE_TOKEN: "user1_secret_token"
      UPTRACE_PROJECT_ID: "1"
    cmds:
      - |
        echo "Waiting for Uptrace to be ready..."
        timeout 120 bash -c 'until curl -f http://localhost:14318/internal/v1/projects/1/monitors -H "Authorization: Bearer user1_secret_token" 2>/dev/null; do sleep 2; done'
      - go test -v -coverprofile=coverage-acc.txt -covermode=atomic -timeout 30m ./internal/provider -run TestAcc
      - go tool cover -html=coverage-acc.txt -o coverage-acc.html
      - echo "Acceptance test coverage report generated at coverage-acc.html"

  test:coverage:all:
    desc: Run all tests with coverage and merge reports
    cmds:
      - task: test:coverage:unit
      - task: test:coverage:acc
      - echo "Combined coverage reports:"
      - echo "  Unit tests:       coverage.html"
      - echo "  Acceptance tests: coverage-acc.html"

  test:acc:
    desc: Run acceptance tests with Docker
    deps: [dev:up]
    env:
      TF_ACC: "1"
      UPTRACE_ENDPOINT: "http://localhost:14318/internal/v1"
      UPTRACE_TOKEN: "user1_secret_token"
      UPTRACE_PROJECT_ID: "1"
    cmds:
      - |
        echo "Waiting for Uptrace to be ready..."
        timeout 120 bash -c 'until curl -f http://localhost:14318/internal/v1/projects/1/monitors -H "Authorization: Bearer user1_secret_token" 2>/dev/null; do sleep 2; done'
      - go test -v -timeout 30m ./internal/provider -run TestAcc

  test:acc:metric:
    desc: Run metric monitor acceptance tests only
    deps: [dev:up]
    env:
      TF_ACC: "1"
      UPTRACE_ENDPOINT: "http://localhost:14318/internal/v1"
      UPTRACE_TOKEN: "user1_secret_token"
      UPTRACE_PROJECT_ID: "1"
    cmds:
      - go test -v -run TestAccMonitorResource_Metric ./internal/provider/

  test:acc:error:
    desc: Run error monitor acceptance tests only
    deps: [dev:up]
    env:
      TF_ACC: "1"
      UPTRACE_ENDPOINT: "http://localhost:14318/internal/v1"
      UPTRACE_TOKEN: "user1_secret_token"
      UPTRACE_PROJECT_ID: "1"
    cmds:
      - go test -v -run TestAccMonitorResource_Error ./internal/provider/

  test:cloud:
    desc: Run acceptance tests against Uptrace cloud (requires UPTRACE_TOKEN env var)
    env:
      TF_ACC: "1"
      UPTRACE_ENDPOINT: "https://api2.uptrace.dev/internal/v1"
      UPTRACE_TOKEN: "{{.UPTRACE_TOKEN}}"
      UPTRACE_PROJECT_ID: "{{.UPTRACE_PROJECT_ID}}"
    cmds:
      - |
        if [ -z "$UPTRACE_TOKEN" ] || [ -z "$UPTRACE_PROJECT_ID" ]; then
          echo "Error: UPTRACE_TOKEN and UPTRACE_PROJECT_ID environment variables must be set"
          echo "Example: export UPTRACE_TOKEN=your-token UPTRACE_PROJECT_ID=your-project-id"
          exit 1
        fi
      - go test -v -timeout 10m ./internal/provider -run TestAccMonitorResource_CloudTrendAggregation

  test:cloud:send-telemetry:
    desc: Send test telemetry data to Uptrace cloud for testing
    cmds:
      - ./scripts/send-test-telemetry.sh

  test:all:
    desc: Run all tests (unit + acceptance)
    cmds:
      - task: test:unit
      - task: test:acc

  testacc:
    desc: Legacy acceptance test command (use test:acc instead)
    cmds:
      - task: test:acc

  lint:
    desc: Run linters
    deps: [generate]
    cmds:
      - golangci-lint run --timeout 5m

  lint:fix:
    desc: Run linters and auto-fix issues
    deps: [generate]
    cmds:
      - golangci-lint run --fix --timeout 5m

  fmt:
    desc: Format code
    cmds:
      - gofmt -s -w .
      - go mod tidy

  docs:
    desc: Generate provider documentation
    deps: [build]
    cmds:
      - tfplugindocs generate --provider-name uptrace

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.txt coverage.html
      - rm -rf dist/
      - rm -rf .test/

  clean:all:
    desc: Clean all generated files including client code
    deps: [clean]
    cmds:
      - rm -rf internal/client/generated/

  validate:
    desc: Run all validation checks
    deps: [generate]
    cmds:
      - task: fmt
      - task: lint
      - task: test

  release:
    desc: Create a new release (dry-run)
    cmds:
      - goreleaser release --snapshot --clean

  release:publish:
    desc: Publish a new release
    cmds:
      - goreleaser release --clean

  dev:setup:
    desc: Complete development environment setup
    cmds:
      - task: deps
      - task: generate
      - task: build
      - echo "Development environment ready!"

  dev:up:
    desc: Start local Uptrace instance for testing
    dir: dev-env
    cmds:
      - docker compose up -d
      - echo "Waiting for Uptrace to be ready..."
      - |
        for i in {1..60}; do
          if docker compose logs uptrace 2>&1 | grep -q "serving GRPC"; then
            echo "✅ Uptrace is ready!"
            echo ""
            echo "📊 Web UI:        http://localhost:14318"
            echo "   Email:         admin@uptrace.local"
            echo "   Password:      SomeRandomPassword"
            echo "   API Token:     user1_secret_token (for provider testing)"
            echo ""
            echo "Next steps:"
            echo "1. Copy dev-env/terraform-test/terraform.tfvars.example to terraform.tfvars"
            echo "2. Add the token above to terraform.tfvars"
            echo "3. Run: task dev:test"
            exit 0
          fi
          sleep 2
        done
        echo "❌ Uptrace failed to start"
        exit 1

  dev:down:
    desc: Stop local Uptrace instance
    dir: dev-env
    cmds:
      - docker compose down

  dev:reset:
    desc: Reset local Uptrace instance (removes all data)
    dir: dev-env
    cmds:
      - docker compose down -v
      - echo "All data removed. Run 'task dev:up' to start fresh."

  dev:logs:
    desc: Show Uptrace logs
    dir: dev-env
    cmds:
      - docker compose logs -f uptrace

  dev:test:
    desc: Test provider against local Uptrace
    dir: dev-env/terraform-test
    deps: [install]
    cmds:
      - tofu init -upgrade
      - tofu plan
      - echo ""
      - echo "Review the plan above. To apply, run:"
      - echo "  cd dev-env/terraform-test && tofu apply"

  dev:install-local:
    desc: Install provider locally for testing
    deps: [build]
    vars:
      VERSION: '0.1.0'
      OS: '{{OS}}'
      ARCH: '{{ARCH}}'
    cmds:
      - mkdir -p ~/.terraform.d/plugins/registry.terraform.io/riccap/uptrace/{{.VERSION}}/{{.OS}}_{{.ARCH}}
      - cp {{.BINARY_NAME}} ~/.terraform.d/plugins/registry.terraform.io/riccap/uptrace/{{.VERSION}}/{{.OS}}_{{.ARCH}}/
      - echo "Provider installed to ~/.terraform.d/plugins/registry.terraform.io/riccap/uptrace/{{.VERSION}}/{{.OS}}_{{.ARCH}}/"
