name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: |
        What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Configure provider with...
        2. Apply configuration...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Terraform/OpenTofu Configuration
      description: The relevant configuration that triggers the bug
      placeholder: |
        resource "uptrace_monitor" "example" {
          name = "Test Monitor"
          type = "metric"
          # ... rest of config
        }
      render: hcl
    validations:
      required: true

  - type: textarea
    id: error
    attributes:
      label: Error Output
      description: The complete error message or unexpected output
      placeholder: |
        Paste the full error output here, including stack traces if available.
      render: shell

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?

  - type: input
    id: provider_version
    attributes:
      label: Provider Version
      description: Which version of the provider are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: tofu_version
    attributes:
      label: OpenTofu/Terraform Version
      description: Output of `tofu version` or `terraform version`
      placeholder: "OpenTofu v1.6.0"
    validations:
      required: true

  - type: input
    id: uptrace_version
    attributes:
      label: Uptrace Version
      description: Which version of Uptrace are you using?
      placeholder: "2.0.1"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information (logs, screenshots, etc.)
