name: Test Implementation
description: Track test implementation work
title: "[Test]: "
labels: ["testing"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to track test implementation tasks for the provider.

  - type: dropdown
    id: test_type
    attributes:
      label: Test Type
      description: What kind of test are you implementing?
      options:
        - Unit Test
        - Acceptance Test
        - Integration Test
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is being tested?
      options:
        - Monitor Resource
        - Monitor Data Source
        - Notification Channel Resource
        - Dashboard Resource
        - Team Resource
        - Client Wrapper
        - Model Conversions
        - Provider Configuration
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Test Description
      description: What functionality is being tested?
      placeholder: |
        Describe the test scope and what it validates.

        Example: Test full CRUD lifecycle for metric monitors, including create, read, update, delete, and import operations.
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Test Implementation Checklist
      description: Track progress on test implementation
      options:
        - label: Test file created
        - label: Happy path test cases implemented
        - label: Error cases covered
        - label: Edge cases covered
        - label: Tests pass locally
        - label: CI passing
        - label: Code coverage > 80%
        - label: Documentation updated (if needed)

  - type: textarea
    id: test_files
    attributes:
      label: Test Files
      description: List the test files being created or modified
      placeholder: |
        - internal/provider/monitor_resource_test.go
        - internal/acctest/fixtures.go

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any blockers or dependencies?
      placeholder: |
        - Requires Docker environment
        - Depends on Issue #X
        - Needs API endpoint documentation

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Any additional context or implementation details
